name: Build Android App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build debug version
      run: ./gradlew assembleDebug

    - name: Copy debug APK to artifacts
      run: cp app/build/outputs/apk/debug/app-debug.apk $GITHUB_WORKSPACE/app-debug.apk

    - name: Upload debug APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: $GITHUB_WORKSPACE/app-debug.apk

    - name: Build release version
      run: ./gradlew bundleRelease

    - name: Copy release bundle to artifacts
      run: cp app/build/outputs/bundle/release/app-release.aab $GITHUB_WORKSPACE/app-release.aab

    - name: Upload release bundle as artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-bundle
        path: $GITHUB_WORKSPACE/app-release.aab
